[package]
name = "ax-rnd"
version = "0.1.5"
edition = "2024"
authors = ["Bagus Dwi Harianto robbymangkualam2000@gmail.com"]
license = "MIT"
repository = "https://github.com/robby031/ax-rnd"
description = "AxRng is a fast, small random number generator (rng) library and CLI tool written in Rust."
keywords = ["rng", "random", "uuid", "token", "shuffle"]
categories = ["algorithms", "no-std", "command-line-utilities"]
readme = "README.md"

[features]
std = []
default = ["std"]

[lib]
name = "ax_rnd"

[[bin]]
name = "ax_rnd"
path = "src/main.rs"

[profile.release]
debug = true

[profile.bench]
debug = true

[dependencies]

[dev-dependencies]
criterion = "0.5"
rand = "0.9"
fastrand = "2"


[[bench]]
name = "competitors_bench"
harness = false

[[bench]]
name = "axrnd_bench"
harness = false
